# Stage 1: Build the React Vite project
FROM node:14.17.0-alpine as builder
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the project files
COPY frontend .

# Build the project
RUN npm run build

# Stage 2: Serve the built files using Nginx
FROM nginx:1.21.0-alpine

# Copy custom nginx configuration
COPY ./nginx/app.conf /etc/nginx/conf.d/default.conf

# Copy the built files from the previous stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose the container port
EXPOSE 80
EXPOSE 443


# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

