export const preferenceOptions = [
  "Adventure sports and activities",
  "Art and cultural",
  "Beaches and water activities",
  "Beer and wine tasting",
  "Boat tours and cruises",
  "beaches and water activities",
  "Botanical gardens and arboretums",
  "Caving and spelunking",
  "Children's museums and science centers",
  "Road cycling and bike trails",
  "Family-friendly activities and destinations",
  "Family-friendly hiking and biking trails",
  "Family-friendly interactive experiences",
  "Family-friendly beaches and waterfronts",
  "Farm visits and petting zoos",
  "Festivals and fairs for families",
  "Food and dining experiences",
  "Food and wine",
  "Ghost and haunted houses",
  "Golf courses and resorts",
  "Hiking trails (up to half-day)",
  "Hiking trails (full-day)",
  "Historical sites and landmarks",
  "Hot springs and thermal baths",
  "Local art and handicrafts",
  "Local markets and food stalls",
  "Mountain biking and cycling trails",
  "Nightlife and entertainment",
  "Off-road and ATV adventures",
  "Photography and Instagrammable spots",
  "Romantic getaways and honeymoon destinations",
  "Scenic drives and road trips",
  "Scuba diving and snorkeling destinations",
  "Shopping and markets",
  "Spiritual and religious sites",
  "Street art, graffiti and pusblic sculptures",
  "Theme parks and amusement parks",
  "Water parks and pools",
  "Wellness and relaxation experiences",
  "Wildlife and nature reserves",
  "Yoga and meditation retreats",
  "Zoos and aquariums",
];
